# This is a basic workflow to help you get started with Actions

name: Bootcamp CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
     amb:
          description: 'Selecionar algum destes ambientes: dev / stg / hlg / prd / qa'
          required: false
          default: 'qa'
          
    browser:
          description: 'Selecionar algum destes browsers: chrome / electron'
          required: true
          default: 'chrome'
          
env:
  DEFAULT_KEY: "c72f7e7e-669a-4ce8-a72a-3fcf65ffa4fd"
  DEFAULT_AMB: "qa"
  DEFAULT_BROWSER: "chrome"
  DEFAULT_GROUP: "Contiuos-Testing"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run-tests:
    name: Cypress run
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome96-ff94
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

   

      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        with: 
          command: npx cypress run --record --parallel --group ${{env.DEFAULT_GROUP}} --key ${{env.DEFAULT_KEY}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}} --env version=${{github.event.inputs.amb || env.DEFAULT_AMB}}

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
